# Air Quality Prediction using OpenAQ + NASA POWER
# Author: Reesha and Eesha Waqar
# Description: This notebook collects, processes, and prepares data for AQI prediction.

In [1]:
import requests
import pandas as pd
import numpy as np

In [2]:
city = "Lahore"
lat = 31.5204
lon = 74.3587

start_date = "20220101"
end_date = "20231231"

In [3]:
nasa_url = (
    "https://power.larc.nasa.gov/api/temporal/daily/point"
    f"?parameters=T2M,RH2M,WS2M"
    f"&community=RE"
    f"&longitude={lon}"
    f"&latitude={lat}"
    f"&start={start_date}"
    f"&end={end_date}"
    f"&format=JSON"
)

response = requests.get(nasa_url)
data = response.json()

weather = pd.DataFrame(data["properties"]["parameter"])
weather.index = pd.to_datetime(weather.index)
weather = weather.reset_index().rename(columns={"index": "date"})

weather.head()

        date    T2M   RH2M  WS2M
0 2022-01-01  12.42  44.13  1.09
1 2022-01-02  12.92  45.62  1.37
2 2022-01-03  13.75  52.70  1.28
3 2022-01-04  12.59  69.26  1.51
4 2022-01-05  12.47  90.84  0.87

In [4]:
weather.info()
weather.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 730 entries, 0 to 729
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    730 non-null    datetime64[ns]
 1   T2M     730 non-null    float64
 2   RH2M    730 non-null    float64
 3   WS2M    730 non-null    float64
dtypes: datetime64[ns](1), float64(3)
memory usage: 22.9 KB

                      date         T2M        RH2M        WS2M
count                  730  730.000000  730.000000  730.000000
mean   2022-12-31 12:00:00   24.684699   55.151301    1.467521
min    2022-01-01 00:00:00    7.540000    9.500000    0.430000
25%    2022-07-02 06:00:00   17.472500   42.505000    1.090000
50%    2022-12-31 12:00:00   26.340000   56.985000    1.365000
75%    2023-07-01 18:00:00   30.515000   70.225000    1.725000
max    2023-12-31 00:00:00   39.890000   91.090000    5.090000
std                    NaN    7.874185   18.946857    0.539455

In [6]:
headers = {
    "X-API-Key": "e67f495428ae4db02e150d673eccf5a9dcb75f07aba85f91bfc078a9d995e7f4"
}

locations_url = "https://api.openaq.org/v3/locations"

params = {
    "coordinates": f"{lat},{lon}",
    "radius": 25000,
    "limit": 20
}

response = requests.get(locations_url, params=params, headers=headers)
openaq_locations = response.json()

openaq_locations

{'meta': {'name': 'openaq-api',
  'website': '/',
  'page': 1,
  'limit': 20,
  'found': '>20'},
 'results': [{'id': 8664,
   'name': 'US Diplomatic Post: Lahore',
   'locality': 'Lahore',
   'timezone': 'Asia/Karachi',
   'country': {'id': 109, 'code': 'PK', 'name': 'Pakistan'},
   'owner': {'id': 4, 'name': 'Unknown Governmental Organization'},
   'provider': {'id': 265, 'name': 'StateAir Lahore'},
   'isMobile': False,
   'isMonitor': True,
   'instruments': [{'id': 2, 'name': 'Government Monitor'}],
   'sensors': [{'id': 25135,
     'name': 'pm25 µg/m³',
     'parameter': {'id': 2,
      'name': 'pm25',
      'units': 'µg/m³',
      'displayName': 'PM2.5'}}],
   'coordinates': {'latitude': 31.560078, 'longitude': 74.33589},
   'licenses': None,
   'bounds': [74.33589, 31.560078, 74.33589, 31.560078],
   'distance': 4903.77691267,
   'datetimeFirst': {'utc': '2019-05-22T22:00:00Z',
    'local': '2019-05-23T03:00:00+05:00'},
   'datetimeLast': {'utc': '2025-03-04T12:00:00Z',
    'local': '2025-03-04T17:00:00+05:00'}},
  {'id': 1894641,
   'name': 'Lahore',
   'locality': None,
   'timezone': 'Asia/Karachi',
   'country': {'id': 109, 'code': 'PK', 'name': 'Pakistan'},
   'owner': {'id': 9, 'name': 'Clarity'},
   'provider': {'id': 166, 'name': 'Clarity'},
   'isMobile': False,
   'isMonitor': False,
   'instruments': [{'id': 4, 'name': 'Clarity Sensor'}],
   'sensors': [{'id': 7466363,
     'name': 'pm1 µg/m³',
     'parameter': {'id': 19,
      'name': 'pm1',
      'units': 'µg/m³',
      'displayName': 'PM1'}},
    {'id': 7466364,
     'name': 'pm10 µg/m³',
     'parameter': {'id': 1,
      'name': 'pm10',
      'units': 'µg/m³',
      'displayName': 'PM10'}},
    {'id': 7466365,
     'name': 'pm25 µg/m³',
     'parameter': {'id': 2,
      'name': 'pm25',
      'units': 'µg/m³',
      'displayName': 'PM2.5'}},
    {'id': 7466367,
     'name': 'temperature f',
     'parameter': {'id': 128,
      'name': 'temperature',
      'units': 'f',
      'displayName': 'Temperature (F)'}},
    {'id': 7466366,
     'name': 'temperature c',
     'parameter': {'id': 100,
      'name': 'temperature',
      'units': 'c',
      'displayName': 'Temperature (C)'}}],
   'coordinates': {'latitude': 31.54815, 'longitude': 74.34396},
   'licenses': [{'id': 38,
     'name': 'CC0 1.0',
     'attribution': {'name': 'Clarity', 'url': None},
     'dateFrom': '2021-10-20',
     'dateTo': None}],
   'bounds': [74.34396, 31.54815, 74.34396, 31.54815],
   'distance': 3380.34289874,
   'datetimeFirst': {'utc': '2023-11-28T16:58:05Z',
    'local': '2023-11-28T21:58:05+05:00'},
   'datetimeLast': {'utc': '2026-04-24T13:00:50Z',
    'local': '2026-04-24T18:00:50+05:00'}},
  {'id': 4515157,
   'name': 'Barki, Lahore',
   'locality': None,
   'timezone': 'Asia/Karachi',
   'country': {'id': 109, 'code': 'PK', 'name': 'Pakistan'},
   'owner': {'id': 12, 'name': 'AirGradient'},
   'provider': {'id': 66, 'name': 'AirGradient'},
   'isMobile': False,
   'isMonitor': False,
   'instruments': [{'id': 24,
     'name': 'AirGradient Open Air Generation 1 (O-1PST)'}],
   'sensors': [{'id': 13137725,
     'name': 'pm1 µg/m³',
     'parameter': {'id': 19,
      'name': 'pm1',
      'units': 'µg/m³',
      'displayName': 'PM1'}},
    {'id': 13137726,
     'name': 'pm25 µg/m³',
     'parameter': {'id': 2,
      'name': 'pm25',
      'units': 'µg/m³',
      'displayName': 'PM2.5'}},
    {'id': 13137727,
     'name': 'relativehumidity %',
     'parameter': {'id': 98,
      'name': 'relativehumidity',
      'units': '%',
      'displayName': 'RH'}},
    {'id': 13137728,
     'name': 'temperature c',
     'parameter': {'id': 100,
      'name': 'temperature',
      'units': 'c',
      'displayName': 'Temperature (C)'}},
    {'id': 13137729,
     'name': 'um003 particles/cm³',
     'parameter': {'id': 125,
      'name': 'um003',
      'units': 'particles/cm³',
      'displayName': 'PM0.3 count'}}],
   'coordinates': {'latitude': 31.4591591, 'longitude': 74.5396309},
   'licenses': [{'id': 41,
     'name': 'CC BY 4.0',
     'attribution': {'name': 'AirGradient', 'url': None},
     'dateFrom': '2023-07-15',
     'dateTo': None}],
   'bounds': [74.5396309, 31.4591591, 74.5396309, 31.4591591],
   'distance': 18483.19727992,
   'datetimeFirst': {'utc': '2025-05-24T17:00:00Z',
    'local': '2025-05-24T22:00:00+05:00'},
   'datetimeLast': {'utc': '2026-04-24T13:00:00Z',
    'local': '2026-04-24T18:00:00+05:00'}},
  {'id': 4527035,
   'name': 'Civil Secretariat',
   'locality': None,
   'timezone': 'Asia/Karachi',
   'country': {'id': 109, 'code': 'PK', 'name': 'Pakistan'},
   'owner': {'id': 16818, 'name': 'The Urban Unit'},
   'provider': {'id': 66, 'name': 'AirGradient'},
   'isMobile': False,
   'isMonitor': False,
   'instruments': [{'id': 24,
     'name': 'AirGradient Open Air Generation 1 (O-1PST)'}],
   'sensors': [{'id': 13153586,
     'name': 'pm1 µg/m³',
     'parameter': {'id': 19,
      'name': 'pm1',
      'units': 'µg/m³',
      'displayName': 'PM1'}},
    {'id': 13153587,
     'name': 'pm25 µg/m³',
     'parameter': {'id': 2,
      'name': 'pm25',
      'units': 'µg/m³',
      'displayName': 'PM2.5'}},
    {'id': 13153588,
     'name': 'relativehumidity %',
     'parameter': {'id': 98,
      'name': 'relativehumidity',
      'units': '%',
      'displayName': 'RH'}},
    {'id': 13153589,
     'name': 'temperature c',
     'parameter': {'id': 100,
      'name': 'temperature',
      'units': 'c',
      'displayName': 'Temperature (C)'}},
    {'id': 13153590,
     'name': 'um003 particles/cm³',
     'parameter': {'id': 125,
      'name': 'um003',
      'units': 'particles/cm³',
      'displayName': 'PM0.3 count'}}],
   'coordinates': {'latitude': 31.565942, 'longitude': 74.2993626},
   'licenses': [{'id': 41,
     'name': 'CC BY 4.0',
     'attribution': {'name': 'The Urban Unit', 'url': None},
     'dateFrom': '2023-07-15',
     'dateTo': None}],
   'bounds': [74.2993626, 31.565942, 74.2993626, 31.565942],
   'distance': 7566.2150642,
   'datetimeFirst': {'utc': '2025-05-26T07:00:00Z',
    'local': '2025-05-26T12:00:00+05:00'},
   'datetimeLast': {'utc': '2026-03-26T21:00:00Z',
    'local': '2026-03-27T02:00:00+05:00'}},
  {'id': 4527173,
   'name': 'Learning Alliance Intl. DHA',
   'locality': None,
   'timezone': 'Asia/Karachi',
   'country': {'id': 109, 'code': 'PK', 'name': 'Pakistan'},
   'owner': {'id': 16818, 'name': 'The Urban Unit'},
   'provider': {'id': 66, 'name': 'AirGradient'},
   'isMobile': False,
   'isMonitor': False,
   'instruments': [{'id': 24,
     'name': 'AirGradient Open Air Generation 1 (O-1PST)'}],
   'sensors': [{'id': 13154527,
     'name': 'pm1 µg/m³',
     'parameter': {'id': 19,
      'name': 'pm1',
      'units': 'µg/m³',
      'displayName': 'PM1'}},
    {'id': 13154528,
     'name': 'pm25 µg/m³',
     'parameter': {'id': 2,
      'name': 'pm25',
      'units': 'µg/m³',
      'displayName': 'PM2.5'}},
    {'id': 13154529,
     'name': 'relativehumidity %',
     'parameter': {'id': 98,
      'name': 'relativehumidity',
      'units': '%',
      'displayName': 'RH'}},
    {'id': 13154530,
     'name': 'temperature c',
     'parameter': {'id': 100,
      'name': 'temperature',
      'units': 'c',
      'displayName': 'Temperature (C)'}},
    {'id': 13154531,
     'name': 'um003 particles/cm³',
     'parameter': {'id': 125,
      'name': 'um003',
      'units': 'particles/cm³',
      'displayName': 'PM0.3 count'}}],
   'coordinates': {'latitude': 31.525621, 'longitude': 74.436078},
   'licenses': [{'id': 41,
     'name': 'CC BY 4.0',
     'attribution': {'name': 'The Urban Unit', 'url': None},
     'dateFrom': '2023-07-15',
     'dateTo': None}],
   'bounds': [74.436078, 31.525621, 74.436078, 31.525621],
   'distance': 7372.05288221,
   'datetimeFirst': {'utc': '2025-05-26T09:00:00Z',
    'local': '2025-05-26T14:00:00+05:00'},
   'datetimeLast': {'utc': '2026-04-24T13:00:00Z',
    'local': '2026-04-24T18:00:00+05:00'}},
  {'id': 4527306,
   'name': 'FOOT & MOUTH DISEASE RESEARCH CENTRE',
   'locality': None,
   'timezone': 'Asia/Karachi',
   'country': {'id': 109, 'code': 'PK', 'name': 'Pakistan'},
   'owner': {'id': 16818, 'name': 'The Urban Unit'},
   'provider': {'id': 66, 'name': 'AirGradient'},
   'isMobile': False,
   'isMonitor': False,
   'instruments': [{'id': 24,
     'name': 'AirGradient Open Air Generation 1 (O-1PST)'}],
   'sensors': [{'id': 13155468,
     'name': 'pm1 µg/m³',
     'parameter': {'id': 19,
      'name': 'pm1',
      'units': 'µg/m³',
      'displayName': 'PM1'}},
    {'id': 13155469,
     'name': 'pm25 µg/m³',
     'parameter': {'id': 2,
      'name': 'pm25',
      'units': 'µg/m³',
      'displayName': 'PM2.5'}},
    {'id': 13155470,
     'name': 'relativehumidity %',
     'parameter': {'id': 98,
      'name': 'relativehumidity',
      'units': '%',
      'displayName': 'RH'}},
    {'id': 13155471,
     'name': 'temperature c',
     'parameter': {'id': 100,
      'name': 'temperature',
      'units': 'c',
      'displayName': 'Temperature (C)'}},
    {'id': 13155472,
     'name': 'um003 particles/cm³',
     'parameter': {'id': 125,
      'name': 'um003',
      'units': 'particles/cm³',
      'displayName': 'PM0.3 count'}}],
   'coordinates': {'latitude': 31.53574, 'longitude': 74.43538},
   'licenses': [{'id': 41,
     'name': 'CC BY 4.0',
     'attribution': {'name': 'The Urban Unit', 'url': None},
     'dateFrom': '2023-07-15',
     'dateTo': None}],
   'bounds': [74.43538, 31.53574, 74.43538, 31.53574],
   'distance': 7478.58646315,
   'datetimeFirst': {'utc': '2025-05-26T11:00:00Z',
    'local': '2025-05-26T16:00:00+05:00'},
   'datetimeLast': {'utc': '2026-04-24T13:00:00Z',
    'local': '2026-04-24T18:00:00+05:00'}},
  {'id': 4527402,
   'name': 'HBFC Society, DHA Phase 5 (Hussainy House)',
   'locality': None,
   'timezone': 'Asia/Karachi',
   'country': {'id': 109, 'code': 'PK', 'name': 'Pakistan'},
   'owner': {'id': 16818, 'name': 'The Urban Unit'},
   'provider': {'id': 66, 'name': 'AirGradient'},
   'isMobile': False,
   'isMonitor': False,
   'instruments': [{'id': 24,
     'name': 'AirGradient Open Air Generation 1 (O-1PST)'}],
   'sensors': [{'id': 13156082,
     'name': 'pm1 µg/m³',
     'parameter': {'id': 19,
      'name': 'pm1',
      'units': 'µg/m³',
      'displayName': 'PM1'}},
    {'id': 13156083,
     'name': 'pm25 µg/m³',
     'parameter': {'id': 2,
      'name': 'pm25',
      'units': 'µg/m³',
      'displayName': 'PM2.5'}},
    {'id': 13156084,
     'name': 'relativehumidity %',
     'parameter': {'id': 98,
      'name': 'relativehumidity',
      'units': '%',
      'displayName': 'RH'}},
    {'id': 13156085,
     'name': 'temperature c',
     'parameter': {'id': 100,
      'name': 'temperature',
      'units': 'c',
      'displayName': 'Temperature (C)'}},
    {'id': 13156086,
     'name': 'um003 particles/cm³',
     'parameter': {'id': 125,
      'name': 'um003',
      'units': 'particles/cm³',
      'displayName': 'PM0.3 count'}}],
   'coordinates': {'latitude': 31.4571645, 'longitude': 74.4106586},
   'licenses': [{'id': 41,
     'name': 'CC BY 4.0',
     'attribution': {'name': 'The Urban Unit', 'url': None},
     'dateFrom': '2023-07-15',
     'dateTo': None}],
   'bounds': [74.4106586, 31.4571645, 74.4106586, 31.4571645],
   'distance': 8575.06651497,
   'datetimeFirst': {'utc': '2025-05-26T13:00:00Z',
    'local': '2025-05-26T18:00:00+05:00'},
   'datetimeLast': {'utc': '2026-04-24T13:00:00Z',
    'local': '2026-04-24T18:00:00+05:00'}},
  {'id': 4535267,
   'name': 'Gajju Matta (Kahna)',
   'locality': None,
   'timezone': 'Asia/Karachi',
   'country': {'id': 109, 'code': 'PK', 'name': 'Pakistan'},
   'owner': {'id': 16818, 'name': 'The Urban Unit'},
   'provider': {'id': 66, 'name': 'AirGradient'},
   'isMobile': False,
   'isMonitor': False,
   'instruments': [{'id': 7, 'name': 'Unknown AirGradient Sensor'}],
   'sensors': [{'id': 13163332,
     'name': 'pm1 µg/m³',
     'parameter': {'id': 19,
      'name': 'pm1',
      'units': 'µg/m³',
      'displayName': 'PM1'}},
    {'id': 13163333,
     'name': 'pm25 µg/m³',
     'parameter': {'id': 2,
      'name': 'pm25',
      'units': 'µg/m³',
      'displayName': 'PM2.5'}},
    {'id': 13163334,
     'name': 'relativehumidity %',
     'parameter': {'id': 98,
      'name': 'relativehumidity',
      'units': '%',
      'displayName': 'RH'}},
    {'id': 13163335,
     'name': 'temperature c',
     'parameter': {'id': 100,
      'name': 'temperature',
      'units': 'c',
      'displayName': 'Temperature (C)'}},
    {'id': 13163336,
     'name': 'um003 particles/cm³',
     'parameter': {'id': 125,
      'name': 'um003',
      'units': 'particles/cm³',
      'displayName': 'PM0.3 count'}}],
   'coordinates': {'latitude': 31.377378, 'longitude': 74.350574},
   'licenses': [{'id': 41,
     'name': 'CC BY 4.0',
     'attribution': {'name': 'The Urban Unit', 'url': None},
     'dateFrom': '2023-07-15',
     'dateTo': None}],
   'bounds': [74.350574, 31.377378, 74.350574, 31.377378],
   'distance': 15876.68072933,
   'datetimeFirst': {'utc': '2025-05-27T07:00:00Z',
    'local': '2025-05-27T12:00:00+05:00'},
   'datetimeLast': {'utc': '2026-03-07T09:00:00Z',
    'local': '2026-03-07T14:00:00+05:00'}},
  {'id': 4554729,
   'name': 'Sandha Road',
   'locality': None,
   'timezone': 'Asia/Karachi',
   'country': {'id': 109, 'code': 'PK', 'name': 'Pakistan'},
   'owner': {'id': 16818, 'name': 'The Urban Unit'},
   'provider': {'id': 66, 'name': 'AirGradient'},
   'isMobile': False,
   'isMonitor': False,
   'instruments': [{'id': 24,
     'name': 'AirGradient Open Air Generation 1 (O-1PST)'}],
   'sensors': [{'id': 13182279,
     'name': 'pm1 µg/m³',
     'parameter': {'id': 19,
      'name': 'pm1',
      'units': 'µg/m³',
      'displayName': 'PM1'}},
    {'id': 13182280,
     'name': 'pm25 µg/m³',
     'parameter': {'id': 2,
      'name': 'pm25',
      'units': 'µg/m³',
      'displayName': 'PM2.5'}},
    {'id': 13182281,
     'name': 'relativehumidity %',
     'parameter': {'id': 98,
      'name': 'relativehumidity',
      'units': '%',
      'displayName': 'RH'}},
    {'id': 13182282,
     'name': 'temperature c',
     'parameter': {'id': 100,
      'name': 'temperature',
      'units': 'c',
      'displayName': 'Temperature (C)'}},
    {'id': 13182283,
     'name': 'um003 particles/cm³',
     'parameter': {'id': 125,
      'name': 'um003',
      'units': 'particles/cm³',
      'displayName': 'PM0.3 count'}}],
   'coordinates': {'latitude': 31.562302, 'longitude': 74.3027031},
   'licenses': [{'id': 41,
     'name': 'CC BY 4.0',
     'attribution': {'name': 'The Urban Unit', 'url': None},
     'dateFrom': '2023-07-15',
     'dateTo': None}],
   'bounds': [74.3027031, 31.562302, 74.3027031, 31.562302],
   'distance': 7061.26422422,
   'datetimeFirst': {'utc': '2025-05-29T08:00:00Z',
    'local': '2025-05-29T13:00:00+05:00'},
   'datetimeLast': {'utc': '2026-04-24T13:00:00Z',
    'local': '2026-04-24T18:00:00+05:00'}},
  {'id': 4555745,
   'name': 'Ravi Road',
   'locality': None,
   'timezone': 'Asia/Karachi',
   'country': {'id': 109, 'code': 'PK', 'name': 'Pakistan'},
   'owner': {'id': 16818, 'name': 'The Urban Unit'},
   'provider': {'id': 66, 'name': 'AirGradient'},
   'isMobile': False,
   'isMonitor': False,
   'instruments': [{'id': 24,
     'name': 'AirGradient Open Air Generation 1 (O-1PST)'}],
   'sensors': [{'id': 13183458,
     'name': 'pm1 µg/m³',
     'parameter': {'id': 19,
      'name': 'pm1',
      'units': 'µg/m³',
      'displayName': 'PM1'}},
    {'id': 13183459,
     'name': 'pm25 µg/m³',
     'parameter': {'id': 2,
      'name': 'pm25',
      'units': 'µg/m³',
      'displayName': 'PM2.5'}},
    {'id': 13183460,
     'name': 'relativehumidity %',
     'parameter': {'id': 98,
      'name': 'relativehumidity',
      'units': '%',
      'displayName': 'RH'}},
    {'id': 13183461,
     'name': 'temperature c',
     'parameter': {'id': 100,
      'name': 'temperature',
      'units': 'c',
      'displayName': 'Temperature (C)'}},
    {'id': 13183462,
     'name': 'um003 particles/cm³',
     'parameter': {'id': 125,
      'name': 'um003',
      'units': 'particles/cm³',
      'displayName': 'PM0.3 count'}}],
   'coordinates': {'latitude': 31.602875, 'longitude': 74.300927},
   'licenses': [{'id': 41,
     'name': 'CC BY 4.0',
     'attribution': {'name': 'The Urban Unit', 'url': None},
     'dateFrom': '2023-07-15',
     'dateTo': None}],
   'bounds': [74.300927, 31.602875, 74.300927, 31.602875],
   'distance': 10663.55739334,
   'datetimeFirst': {'utc': '2025-05-29T11:00:00Z',
    'local': '2025-05-29T16:00:00+05:00'},
   'datetimeLast': {'utc': '2026-04-02T07:00:00Z',
    'local': '2026-04-02T12:00:00+05:00'}},
  {'id': 4557686,
   'name': 'Shalimar Town',
   'locality': None,
   'timezone': 'Asia/Karachi',
   'country': {'id': 109, 'code': 'PK', 'name': 'Pakistan'},
   'owner': {'id': 16818, 'name': 'The Urban Unit'},
   'provider': {'id': 66, 'name': 'AirGradient'},
   'isMobile': False,
   'isMonitor': False,
   'instruments': [{'id': 24,
     'name': 'AirGradient Open Air Generation 1 (O-1PST)'}],
   'sensors': [{'id': 13184346,
     'name': 'pm1 µg/m³',
     'parameter': {'id': 19,
      'name': 'pm1',
      'units': 'µg/m³',
      'displayName': 'PM1'}},
    {'id': 13184347,
     'name': 'pm25 µg/m³',
     'parameter': {'id': 2,
      'name': 'pm25',
      'units': 'µg/m³',
      'displayName': 'PM2.5'}},
    {'id': 13184348,
     'name': 'relativehumidity %',
     'parameter': {'id': 98,
      'name': 'relativehumidity',
      'units': '%',
      'displayName': 'RH'}},
    {'id': 13184349,
     'name': 'temperature c',
     'parameter': {'id': 100,
      'name': 'temperature',
      'units': 'c',
      'displayName': 'Temperature (C)'}},
    {'id': 13184350,
     'name': 'um003 particles/cm³',
     'parameter': {'id': 125,
      'name': 'um003',
      'units': 'particles/cm³',
      'displayName': 'PM0.3 count'}}],
   'coordinates': {'latitude': 31.574289, 'longitude': 74.447898},
   'licenses': [{'id': 41,
     'name': 'CC BY 4.0',
     'attribution': {'name': 'The Urban Unit', 'url': None},
     'dateFrom': '2023-07-15',
     'dateTo': None}],
   'bounds': [74.447898, 31.574289, 74.447898, 31.574289],
   'distance': 10365.27939372,
   'datetimeFirst': {'utc': '2025-05-29T13:00:00Z',
    'local': '2025-05-29T18:00:00+05:00'},
   'datetimeLast': {'utc': '2026-04-24T09:00:00Z',
    'local': '2026-04-24T14:00:00+05:00'}},
  {'id': 4565933,
   'name': 'IEEE, Punjab University, LHR',
   'locality': None,
   'timezone': 'Asia/Karachi',
   'country': {'id': 109, 'code': 'PK', 'name': 'Pakistan'},
   'owner': {'id': 16818, 'name': 'The Urban Unit'},
   'provider': {'id': 66, 'name': 'AirGradient'},
   'isMobile': False,
   'isMonitor': False,
   'instruments': [{'id': 24,
     'name': 'AirGradient Open Air Generation 1 (O-1PST)'}],
   'sensors': [{'id': 13190997,
     'name': 'pm1 µg/m³',
     'parameter': {'id': 19,
      'name': 'pm1',
      'units': 'µg/m³',
      'displayName': 'PM1'}},
    {'id': 13190998,
     'name': 'pm25 µg/m³',
     'parameter': {'id': 2,
      'name': 'pm25',
      'units': 'µg/m³',
      'displayName': 'PM2.5'}},
    {'id': 13190999,
     'name': 'relativehumidity %',
     'parameter': {'id': 98,
      'name': 'relativehumidity',
      'units': '%',
      'displayName': 'RH'}},
    {'id': 13191000,
     'name': 'temperature c',
     'parameter': {'id': 100,
      'name': 'temperature',
      'units': 'c',
      'displayName': 'Temperature (C)'}},
    {'id': 13191001,
     'name': 'um003 particles/cm³',
     'parameter': {'id': 125,
      'name': 'um003',
      'units': 'particles/cm³',
      'displayName': 'PM0.3 count'}}],
   'coordinates': {'latitude': 31.495322, 'longitude': 74.295056},
   'licenses': [{'id': 41,
     'name': 'CC BY 4.0',
     'attribution': {'name': 'The Urban Unit', 'url': None},
     'dateFrom': '2023-07-15',
     'dateTo': None}],

In [24]:
# =========================
# CELL 5: Fetch OpenAQ Locations for Lahore
# =========================
locations_url = "https://api.openaq.org/v3/locations"

params = {
    "coordinates": f"{lat},{lon}",
    "radius": 25000,   # ✅ FIXED (max allowed)
    "parameters_id": 2,
    "limit": 100
}

response = requests.get(locations_url, params=params, headers=headers)

print("Status code:", response.status_code)
print(response.text[:500])

# safe parsing
if response.status_code != 200:
    raise Exception("API error, fix this before continuing")

openaq_locations = response.json()

Status code: 200
{"meta":{"name":"openaq-api","website":"/","page":1,"limit":100,"found":80},"results":[{"id":8664,"name":"US Diplomatic Post: Lahore","locality":"Lahore","timezone":"Asia/Karachi","country":{"id":109,"code":"PK","name":"Pakistan"},"owner":{"id":4,"name":"Unknown Governmental Organization"},"provider":{"id":265,"name":"StateAir Lahore"},"isMobile":false,"isMonitor":true,"instruments":[{"id":2,"name":"Government Monitor"}],"sensors":[{"id":25135,"name":"pm25 µg/m³","parameter":{"id":2,"name":"pm25

In [25]:
# =========================
# CELL 6: Display All Retrieved Locations
# =========================
locations = openaq_locations.get("results", [])

print("Total PM2.5 locations found:", len(locations))

for loc in locations:
    print("Location ID:", loc["id"])
    print("Name:", loc.get("name"))
    print("Locality:", loc.get("locality"))
    print("Country:", loc.get("country"))
    print("Parameters:", [p.get("name") for p in loc.get("parameters", [])])
    print("-" * 50)

Total PM2.5 locations found: 80
Location ID: 8664
Name: US Diplomatic Post: Lahore
Locality: Lahore
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 1894641
Name: Lahore
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 4515157
Name: Barki, Lahore
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 4527035
Name: Civil Secretariat
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 4527173
Name: Learning Alliance Intl. DHA
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 4527306
Name: FOOT & MOUTH DISEASE RESEARCH CENTRE
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 4527402
Name: HBFC Society, DHA Phase 5 (Hussainy House)
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 4535267
Name: Gajju Matta (Kahna)
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 4554729
Name: Sandha Road
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 4555745
Name: Ravi Road
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 4557686
Name: Shalimar Town
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 4565933
Name: IEEE, Punjab University, LHR
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 4566427
Name: Johar Town
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 4568423
Name: Model Town
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 4605119
Name: College Road
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 4608421
Name: Assistant Commissioner Office, Allama Iqbal
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 4609353
Name: Kahna Hospital
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 4618814
Name: Gulberg III
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 4698865
Name: Cantonment
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 4699919
Name: Pak Arab
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 4700982
Name: Samanabad
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 4757305
Name: Forman Christian College & Chartered University
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 5371017
Name: Thokar Niaz Baig
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 6093552
Name: Test Device
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 6125629
Name: ARC, Lahore
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 6135289
Name: Bedian Thethar Rd LHE
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 6135293
Name: B Block, Phase 5, DHA
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 6135295
Name: Pakistan Engineering Services (Pvt) Ltd.
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 6135299
Name: Yani Home
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 6135301
Name: Grand Charter School
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 6135306
Name: Askari 10
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 6135309
Name: Scarsdale International School
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 6135313
Name: Ghazi Road Interchange
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 6135316
Name: FF Pakistan
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 6135318
Name: WWF-PAKISTAN
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 6135319
Name: Revenue Employees Coop Housing Society
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 6135320
Name: Model Town A LHE
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 6135323
Name: Gurumangat Rd B LHE
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 6135324
Name: Shadman Market B LHE
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 6135326
Name: Ferozepur Rd A LHE
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 6135328
Name: Honda Gateway
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 6135329
Name: LAS Lahore
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 6135330
Name: University of Central Punjab
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 6135333
Name: Trinity School Lahore
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 6135336
Name: Syed Maratib Ali Road
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 6135340
Name: Tufail Road near Rahat Bakery
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 6135343
Name: Powerzone head office
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 6135344
Name: Kickstart MM Alam
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 6135348
Name: HC - Askari 10
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 6135349
Name: Diamond Paint industries PVT LTD.
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 6135350
Name: NPPMCL
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 6135351
Name: Hiking & Mountaineering Club GCU Lahore
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 6135353
Name: The University of Lahore
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 6135356
Name: W.R
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 6135357
Name: VTS
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 6135360
Name: Allama Iqbal Town B LHE
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 6135364
Name: CERP Office
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 6135366
Name: Phase8-DHA
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 6135368
Name: FF Pakistan - 1
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 6135370
Name: Burki Rd B LHE
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 6135373
Name: Climate Finance Pakistan (PakAirQuality)
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 6135374
Name: Near Ada Plot, Raiwind Road
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 6135377
Name: Johar Town B LHE
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 6135421
Name: Model Town B LHE
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 6135457
Name: GENERATION Pvt ltd
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 6135458
Name: Valancia Town Lahore
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 6135466
Name: The Bank of Punjab, Head Office, BOP Tower, Gulberg III.
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 6135473
Name: BAM,  Civil Secretariat
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 6135476
Name: AC OFFICE NISHTAR, GAJUMATA
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 6135493
Name: Samanabad
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 6135496
Name: SOS Johar Town LHR
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 6135507
Name: Model Town, CD Ground
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 6135528
Name: Abdullah Khokhar, House Johar Town
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 6135533
Name: University of Management and Technology
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 6236626
Name: Bahria Town
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 6318813
Name: Upper Mall Road LHR
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 6318816
Name: Burki Rd Paragon B LHE
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 6318817
Name: DHA Phase 6 B LHE
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 6318826
Name: Model Town Link Rd B LHE
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------
Location ID: 6318842
Name: Muslim Town LHE B
Locality: None
Country: {'id': 109, 'code': 'PK', 'name': 'Pakistan'}
Parameters: []
--------------------------------------------------

In [26]:
# =========================
# CELL 7: Find a Location with PM2.5 Sensor
# =========================

pm25_location_id = None
pm25_sensor_id = None
selected_location_name = None

for loc in locations:
    loc_id = loc["id"]
    loc_name = loc.get("name")

    sensors_url = f"https://api.openaq.org/v3/locations/{loc_id}/sensors"
    response = requests.get(sensors_url, headers=headers)

    # Skip if request fails
    if response.status_code != 200:
        continue

    sensors_data = response.json()
    sensors = sensors_data.get("results", [])

    for sensor in sensors:
        param_name = sensor["parameter"]["name"].lower()

        # Check for PM2.5
        if "pm2.5" in param_name or "pm25" in param_name:
            pm25_location_id = loc_id
            pm25_sensor_id = sensor["id"]
            selected_location_name = loc_name

            print("FOUND PM2.5 SENSOR")
            print("Location:", selected_location_name)
            print("Location ID:", pm25_location_id)
            print("Sensor ID:", pm25_sensor_id)
            print("Parameter:", sensor["parameter"]["name"])
            break

    if pm25_sensor_id is not None:
        break

# Final check
if pm25_sensor_id is None:
    print("No PM2.5 sensor found in these locations.")

FOUND PM2.5 SENSOR
Location: US Diplomatic Post: Lahore
Location ID: 8664
Sensor ID: 25135
Parameter: pm25

In [27]:
# =========================
# CELL 8: Fetch PM2.5 Data from Selected Sensor
# =========================

measurements_url = f"https://api.openaq.org/v3/sensors/{pm25_sensor_id}/hours"

params = {
    "datetime_from": "2022-01-01T00:00:00Z",
    "datetime_to": "2023-12-31T23:59:59Z",
    "limit": 1000,
    "page": 1
}

all_results = []

while True:
    response = requests.get(measurements_url, params=params, headers=headers)

    print("Page:", params["page"], "Status:", response.status_code)

    if response.status_code != 200:
        print(response.text[:500])
        break

    data = response.json()
    batch = data.get("results", [])

    print("Rows fetched:", len(batch))

    if len(batch) == 0:
        break

    all_results.extend(batch)
    params["page"] += 1

    # Safety stop
    if params["page"] > 30:
        break

# Convert to DataFrame
air = pd.json_normalize(all_results)

air.head()

Page: 1 Status: 200
Rows fetched: 1000
Page: 2 Status: 200
Rows fetched: 1000
Page: 3 Status: 200
Rows fetched: 1000
Page: 4 Status: 200
Rows fetched: 1000
Page: 5 Status: 200
Rows fetched: 1000
Page: 6 Status: 200
Rows fetched: 1000
Page: 7 Status: 200
Rows fetched: 1000
Page: 8 Status: 200
Rows fetched: 1000
Page: 9 Status: 200
Rows fetched: 1000
Page: 10 Status: 200
Rows fetched: 1000
Page: 11 Status: 200
Rows fetched: 1000
Page: 12 Status: 200
Rows fetched: 1000
Page: 13 Status: 200
Rows fetched: 1000
Page: 14 Status: 200
Rows fetched: 1000
Page: 15 Status: 200
Rows fetched: 1000
Page: 16 Status: 200
Rows fetched: 900
Page: 17 Status: 200
Rows fetched: 0

,value,coordinates,flagInfo.hasFlags,parameter.id,parameter.name,parameter.units,parameter.displayName,period.label,period.interval,period.datetimeFrom.utc,...,coverage.expectedCount,coverage.expectedInterval,coverage.observedCount,coverage.observedInterval,coverage.percentComplete,coverage.percentCoverage,coverage.datetimeFrom.utc,coverage.datetimeFrom.local,coverage.datetimeTo.utc,coverage.datetimeTo.local
0,369.0,None,False,2,pm25,µg/m³,None,1hour,01:00:00,2022-01-01T00:00:00Z,...,1,01:00:00,1,01:00:00,100.0,100.0,2022-01-01T00:00:00Z,2022-01-01T05:00:00+05:00,2022-01-01T01:00:00Z,2022-01-01T06:00:00+05:00
1,337.0,None,False,2,pm25,µg/m³,None,1hour,01:00:00,2022-01-01T01:00:00Z,...,1,01:00:00,1,01:00:00,100.0,100.0,2022-01-01T01:00:00Z,2022-01-01T06:00:00+05:00,2022-01-01T02:00:00Z,2022-01-01T07:00:00+05:00
2,348.0,None,False,2,pm25,µg/m³,None,1hour,01:00:00,2022-01-01T02:00:00Z,...,1,01:00:00,1,01:00:00,100.0,100.0,2022-01-01T02:00:00Z,2022-01-01T07:00:00+05:00,2022-01-01T03:00:00Z,2022-01-01T08:00:00+05:00
3,403.0,None,False,2,pm25,µg/m³,None,1hour,01:00:00,2022-01-01T03:00:00Z,...,1,01:00:00,1,01:00:00,100.0,100.0,2022-01-01T03:00:00Z,2022-01-01T08:00:00+05:00,2022-01-01T04:00:00Z,2022-01-01T09:00:00+05:00
4,531.0,None,False,2,pm25,µg/m³,None,1hour,01:00:00,2022-01-01T04:00:00Z,...,1,01:00:00,1,01:00:00,100.0,100.0,2022-01-01T04:00:00Z,2022-01-01T09:00:00+05:00,2022-01-01T05:00:00Z,2022-01-01T10:00:00+05:00

In [28]:
# =========================
# CELL 9: Inspect Data Columns
# =========================

print("Columns in dataset:")
print(air.columns)

Columns in dataset:
Index(['value', 'coordinates', 'flagInfo.hasFlags', 'parameter.id',
       'parameter.name', 'parameter.units', 'parameter.displayName',
       'period.label', 'period.interval', 'period.datetimeFrom.utc',
       'period.datetimeFrom.local', 'period.datetimeTo.utc',
       'period.datetimeTo.local', 'summary.min', 'summary.q02', 'summary.q25',
       'summary.median', 'summary.q75', 'summary.q98', 'summary.max',
       'summary.avg', 'summary.sd', 'coverage.expectedCount',
       'coverage.expectedInterval', 'coverage.observedCount',
       'coverage.observedInterval', 'coverage.percentComplete',
       'coverage.percentCoverage', 'coverage.datetimeFrom.utc',
       'coverage.datetimeFrom.local', 'coverage.datetimeTo.utc',
       'coverage.datetimeTo.local'],
      dtype='object')

In [31]:
# =========================
# CELL 10: Clean PM2.5 Data (Convert Hourly to Daily Average)
# =========================
#We converted hourly pollution readings into daily averages to align with meteorological data and reduce noise in the time series.

# Step 1: Keep only required columns
air_clean = air[["period.datetimeFrom.utc", "value"]].copy()

# Step 2: Rename columns
air_clean.rename(columns={
    "period.datetimeFrom.utc": "datetime",
    "value": "pm25"
}, inplace=True)

# Step 3: Convert to datetime format
air_clean["datetime"] = pd.to_datetime(air_clean["datetime"])

# Step 4: Extract date only (remove time)
air_clean["date"] = air_clean["datetime"].dt.date

# Step 5: Convert date back to datetime (for merging later)
air_clean["date"] = pd.to_datetime(air_clean["date"])

# Step 6: Group by date and take daily average
air_daily = air_clean.groupby("date")["pm25"].mean().reset_index()

# Preview
air_daily.head()

        date        pm25
0 2022-01-01  309.166667
1 2022-01-02  301.625000
2 2022-01-03  180.791667
3 2022-01-04  124.250000
4 2022-01-05   88.625000

In [33]:
# =========================
# CELL 11: Verify Clean PM2.5 Data
# =========================

print("Shape:", air_daily.shape)
print("Date range:")
print(air_daily["date"].min(), "to", air_daily["date"].max())

print("\nMissing values:")
print(air_daily.isnull().sum())

print("\nSummary statistics:")
print(air_daily.describe())

Shape: (666, 2)
Date range:
2022-01-01 00:00:00 to 2023-12-31 00:00:00

Missing values:
date      0
pm25    142
dtype: int64

Summary statistics:
                                date        pm25
count                            666  524.000000
mean   2022-12-30 22:22:42.162162176  125.191105
min              2022-01-01 00:00:00    2.000000
25%              2022-06-22 06:00:00   50.031250
50%              2022-12-11 12:00:00   89.719697
75%              2023-07-17 18:00:00  173.166667
max              2023-12-31 00:00:00  491.000000
std                              NaN   98.470307

In [35]:
# =========================
# CELL 12: Handle Missing PM2.5 Values
# =========================
# We handled missing PM2.5 values using linear interpolation to preserve temporal trends without introducing bias.

# Sort by date (important)
air_daily = air_daily.sort_values("date")

# Fill missing values using interpolation
air_daily["pm25"] = air_daily["pm25"].interpolate(method="linear")

# Check again
print("Missing values after fix:")
print(air_daily.isnull().sum())

air_daily.head()

Missing values after fix:
date    0
pm25    0
dtype: int64

        date        pm25
0 2022-01-01  309.166667
1 2022-01-02  301.625000
2 2022-01-03  180.791667
3 2022-01-04  124.250000
4 2022-01-05   88.625000

In [36]:
# =========================
# CELL 13: Check NASA Weather Data
# =========================

print("Weather shape:", weather.shape)
print("Weather columns:", weather.columns)

print("\nDate range:")
print(weather["date"].min(), "to", weather["date"].max())

print("\nMissing values:")
print(weather.isnull().sum())

weather.head()

Weather shape: (730, 4)
Weather columns: Index(['date', 'T2M', 'RH2M', 'WS2M'], dtype='object')

Date range:
2022-01-01 00:00:00 to 2023-12-31 00:00:00

Missing values:
date    0
T2M     0
RH2M    0
WS2M    0
dtype: int64

        date    T2M   RH2M  WS2M
0 2022-01-01  12.42  44.13  1.09
1 2022-01-02  12.92  45.62  1.37
2 2022-01-03  13.75  52.70  1.28
3 2022-01-04  12.59  69.26  1.51
4 2022-01-05  12.47  90.84  0.87

In [37]:
# =========================
# CELL 14: Merge PM2.5 Data with NASA Weather Data
# =========================

# Merge both datasets using the common date column
df = pd.merge(air_daily, weather, on="date", how="inner")

# Preview merged dataset
print("Merged dataset shape:", df.shape)
print("\nMissing values:")
print(df.isnull().sum())

df.head()

Merged dataset shape: (666, 5)

Missing values:
date    0
pm25    0
T2M     0
RH2M    0
WS2M    0
dtype: int64

        date        pm25    T2M   RH2M  WS2M
0 2022-01-01  309.166667  12.42  44.13  1.09
1 2022-01-02  301.625000  12.92  45.62  1.37
2 2022-01-03  180.791667  13.75  52.70  1.28
3 2022-01-04  124.250000  12.59  69.26  1.51
4 2022-01-05   88.625000  12.47  90.84  0.87

In [39]:
# =========================
# CELL 15: Add Time-Series Features
# =========================

# Sort by date
df = df.sort_values("date")

# Previous pollution values help predict future pollution
df["pm25_lag_1"] = df["pm25"].shift(1)     # previous day PM2.5
df["pm25_lag_7"] = df["pm25"].shift(7)     # previous week PM2.5

# Extract month for seasonal patterns
df["month"] = df["date"].dt.month

# Smog season flag: Lahore smog is usually worse in Oct-Feb
df["smog_season"] = df["month"].isin([10, 11, 12, 1, 2]).astype(int)

# Remove rows where lag values are missing
df = df.dropna().reset_index(drop=True)

print("Dataset shape after feature engineering:", df.shape)
print("\nMissing values:")
print(df.isnull().sum())

df.head()

Dataset shape after feature engineering: (659, 9)

Missing values:
date           0
pm25           0
T2M            0
RH2M           0
WS2M           0
pm25_lag_1     0
pm25_lag_7     0
month          0
smog_season    0
dtype: int64

,date,pm25,T2M,RH2M,WS2M,pm25_lag_1,pm25_lag_7,month,smog_season
0,2022-01-08,97.791667,13.58,87.86,3.15,117.375000,309.166667,1,1
1,2022-01-09,98.125000,11.25,82.62,1.15,97.791667,301.625000,1,1
2,2022-01-10,218.375000,10.94,74.28,0.94,98.125000,180.791667,1,1
3,2022-01-11,162.500000,9.84,76.73,1.38,218.375000,124.250000,1,1
4,2022-01-12,371.000000,11.16,67.58,0.99,162.500000,88.625000,1,1

In [40]:
# =========================
# CELL 16: Save Final Processed Dataset
# =========================

# Save final cleaned and feature-engineered dataset
df.to_csv("lahore_air_quality_final_dataset.csv", index=False)

print("Final dataset saved successfully!")
print("File name: lahore_air_quality_final_dataset.csv")
print("Final shape:", df.shape)

Final dataset saved successfully!
File name: lahore_air_quality_final_dataset.csv
Final shape: (659, 9)

In [41]:
# =========================
# CELL 17: Download Dataset to Your Computer
# =========================

from google.colab import files

files.download("lahore_air_quality_final_dataset.csv")